#!/bin/sh

$PASTER_PATH="paster"
$CONF_PATH="./samples/cloudooo.conf"

lsb_functions="/etc/rc.d/init.d/functions"
if test -f $lsb_functions ; then
. $lsb_functions
else
  log_success_msg()
  {
    echo " SUCCESS! $@"
  }
  log_failure_msg()
  {
		echo " ERROR! $@"
  }
fi
# complete path of the cloudooo folder
FOLDER=$(cd $(dirname $0); pwd -P)/
# get the pid of the cloudooo
CLOUDOOO_PID=$FOLDER/paster.pid
# complete path of this script
SELF=$FOLDER$(basename $0)

case "$1" in

start)
  $PASTER_PATH serve $CONF_PATH --daemon;;
stop)
  kill -1 `cat $CLOUDOOO_PID`;
  $PASTER_PATH serve $CONF_PATH --stop-daemon;;
restart)
  $SELF stop;
  $SELF start;;
fg)
  $PASTER_PATH serve $CONF_PATH;;
*)
  echo "Usage: ./cloudooo {start|stop|restart}";
  exit 1;;
esac
exit 0
